## 1.1 数据操作

### 1.1.1 基础torch命令

In [1]:
import torch

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
print(x.shape)
print(x.size())

torch.Size([12])
torch.Size([12])


In [6]:
# reshape
print(x.reshape(3,4))
print(x.reshape(-1,4))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [7]:
# zeros 和 ones 张量
print(torch.zeros(3,4))
print(torch.ones(1,2,3))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[[1., 1., 1.],
         [1., 1., 1.]]])


In [9]:
# 随机初始化张量
print(torch.randn(3,4))

tensor([[ 1.8283, -0.5255, -0.1994,  1.5803],
        [ 0.4575,  1.2547,  1.4646,  0.9149],
        [-1.1733,  0.3788, -1.4765,  0.5049]])


In [10]:
# 提供嵌套列表作为张量数组初始化值
print(torch.tensor([[1,2],[2,3]]))

tensor([[1, 2],
        [2, 3]])


### 1.1.2 运算符

In [1]:
import numpy as np

In [4]:
X = torch.arange(12).reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [5]:
A = X.numpy()
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
B = torch.tensor(A)
B

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [20]:
A += 1  # np.array()和torch.tensor()都具有广播机制，而一般的列表与标量之间的运算没有广播机制，只能用列表推导式进行计算
print(A)
print(B)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
